"use client";

import { useWallet } from "@/features/wallet/hooks";
import { useTransactionStore } from "@/features/transactions/state";
import { TransactionCard } from "@/features/transactions/ui/transaction-card";
import { ShieldAlert, Trash2 } from "lucide-react";

export default function TransactionCenterPage() {
  const { isConnected } = useWallet();
  const { transactions, clearTransactions } = useTransactionStore();

  if (!isConnected) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] text-center max-w-md mx-auto space-y-6 animate-in fade-in duration-300">
        <div className="rounded-full bg-orange-500/10 p-4 text-orange-500">
          <ShieldAlert className="h-10 w-10" />
        </div>
        <div className="space-y-2">
          <h2 className="text-2xl font-bold tracking-tight text-white">Connect Wallet</h2>
          <p className="text-sm text-neutral-400">
            Please connect your Stellar wallet using the button in the navigation bar to view your transaction logs.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight bg-gradient-to-r from-white to-neutral-400 bg-clip-text text-transparent">
            Transaction Center
          </h1>
          <p className="text-sm text-neutral-400">
            Track transaction submission logs generated by your interactions.
          </p>
        </div>

        {transactions.length > 0 && (
          <button
            onClick={clearTransactions}
            className="inline-flex items-center gap-1.5 rounded-lg border border-red-500/30 bg-red-950/20 hover:bg-red-950/50 px-3.5 py-2 text-xs font-semibold text-red-400 hover:text-red-300 transition-colors w-fit"
          >
            <Trash2 className="h-4 w-4" />
            Clear History
          </button>
        )}
      </div>

      {/* Transactions List */}
      {transactions.length === 0 ? (
        <div className="rounded-2xl border border-white/5 bg-neutral-950/30 p-12 text-center text-neutral-500 text-sm">
          No transactions recorded on this browser session yet. Staking or resolving a goal will generate logs.
        </div>
      ) : (
        <div className="space-y-4 max-w-3xl">
          {transactions.map((tx) => (
            <TransactionCard key={tx.hash} transaction={tx} />
          ))}
        </div>
      )}
    </div>
  );
}
